apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-rollouts
    helm:
      releaseName: argo-rollouts
      values: |
        dashboard:
          enabled: true
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.39.0
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true